name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

variables:
  - template: variables.yaml

resources:
  repositories: 
    - repository: modules
      type: git
      name: modules

trigger: none

pr: none

stages :
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        displayName: 'install'
        inputs:
          terraformVersion: ${{ variables.terraformVersion }}
      - task: TerraformTaskV1@0
        displayName: 'validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          
  - stage: plan
    dependsOn: [validate]
    condition: succeeded('validate')
    jobs:
      - job: terraform_plan
        steps:
              - checkout: self
              - task: TerraformInstaller@0
                displayName: 'install'
                inputs:
                  terraformVersion: ${{ variables.terraformVersion }}
              - script: |
                  git config --global url."https://$SYSTEM_ACCESSTOKEN@dev.azure.com".insteadOf "https://Org-SAMS@dev.azure.com"
                displayName: 'set extra header'
                env:
                  SYSTEM_ACCESSTOKEN: $(System.AccessToken)
              # - bash: git config --global http.https://<your_org>@dev.azure.com.extraheader "AUTHORIZATION: bearer $(System.AccessToken)"
              - task: TerraformTaskV2@2
                displayName: 'init'
                inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: ${{ variables.backendServiceArm }}
                  backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
                  backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
                  backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
                  backendAzureRmKey: '${{ variables.Application }}-${{ variables.Environment }}.tfstate'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/${{ variables.Application }}'
              - task: TerraformTaskV1@0
                displayName: 'plan'
                inputs:
                  provider: 'azurerm'
                  command: 'plan'
                  commandOptions: '-input=false -var-file="./${{ variables.Environment }}/${{ variables.Application }}-${{ variables.Environment }}.tfvars"'
                  environmentServiceNameAzureRM: ${{ variables.environmentServiceNameAzureRM }}
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/${{ variables.Application }}'

  - stage: apply
    dependsOn: [plan]
    condition: succeeded('plan')
    jobs:
      - job: terraform_apply
        steps:
              - checkout: self
              - task: TerraformInstaller@0
                displayName: 'install'
                inputs:
                  terraformVersion: ${{ variables.terraformVersion }}
              - task: TerraformTaskV2@2
                displayName: 'init'
                inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: ${{ variables.backendServiceArm }}
                  backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
                  backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
                  backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
                  backendAzureRmKey: '${{ variables.Application }}-${{ variables.Environment }}.tfstate'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/${{ variables.Application }}'
              - task: TerraformTaskV1@0
                displayName: 'apply'
                inputs:
                  provider: 'azurerm'
                  command: 'apply'
                  commandOptions: '-input=false -var-file="./${{ variables.Environment }}/${{ variables.Application }}-${{ variables.Environment }}.tfvars"'
                  environmentServiceNameAzureRM: ${{ variables.environmentServiceNameAzureRM }}
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/${{ variables.Application }}'

  - stage: destroy
    jobs:
      - job: terraform_destroy
        steps:
              - checkout: self
              - task: TerraformInstaller@0
                displayName: 'install'
                inputs:
                  terraformVersion: ${{ variables.terraformVersion }}
              - task: TerraformTaskV2@2
                displayName: 'init'
                inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: ${{ variables.backendServiceArm }}
                  backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
                  backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
                  backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
                  backendAzureRmKey: '${{ variables.Application }}-${{ variables.Environment }}.tfstate'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/${{ variables.Application }}'
              - task: TerraformTaskV1@0
                displayName: 'destroy'
                inputs:
                  provider: 'azurerm'
                  command: 'destroy'
                  commandOptions: '-input=false -var-file="./${{ variables.Environment }}/${{ variables.Application }}-${{ variables.Environment }}.tfvars"'
                  environmentServiceNameAzureRM: ${{ variables.environmentServiceNameAzureRM }}
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/${{ variables.Application }}'